export default {
    REQUESTING: 'REQUESTING',
    FINISHED_REQUEST: 'FINISHED_REQUEST',
    REQUESTING_GETLIST: 'REQUESTING_GETLIST',
    REQUESTING_CART: 'REQUESTING_CART',
    FINISHED_REQUEST_CART: 'FINISHED_REQUEST_CART',
    SUCCESS_GETLIST : 'SUCCESS_GETLIST',
    PLUS_ITEM : 'PLUS_ITEM',
    REDUCE_ITEM : 'REDUCE_ITEM',
    REMOVE_ITEM : 'REMOVE_ITEM'
}